// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: errors.proto

package example2

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiError int32

const (
	// Service unavailable
	ApiError_SERVICE_UNAVAILABLE ApiError = 0
	// Authentication failed
	ApiError_AUTH_FAILED ApiError = 1
	// Permission denied
	ApiError_PERMISSION_DENIED ApiError = 2
	// Rate limit exceeded
	ApiError_RATE_LIMIT_EXCEEDED ApiError = 3
)

// Enum value maps for ApiError.
var (
	ApiError_name = map[int32]string{
		0: "SERVICE_UNAVAILABLE",
		1: "AUTH_FAILED",
		2: "PERMISSION_DENIED",
		3: "RATE_LIMIT_EXCEEDED",
	}
	ApiError_value = map[string]int32{
		"SERVICE_UNAVAILABLE": 0,
		"AUTH_FAILED":         1,
		"PERMISSION_DENIED":   2,
		"RATE_LIMIT_EXCEEDED": 3,
	}
)

func (x ApiError) Enum() *ApiError {
	p := new(ApiError)
	*p = x
	return p
}

func (x ApiError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiError) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (ApiError) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x ApiError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiError.Descriptor instead.
func (ApiError) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x03api\x1a\x13errors/errors.proto*|\n" +
	"\bApiError\x12\x17\n" +
	"\x13SERVICE_UNAVAILABLE\x10\x00\x12\x15\n" +
	"\vAUTH_FAILED\x10\x01\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11PERMISSION_DENIED\x10\x02\x1a\x04\xa8E\x93\x03\x12\x1d\n" +
	"\x13RATE_LIMIT_EXCEEDED\x10\x03\x1a\x04\xa8E\xad\x03\x1a\x04\xa0E\xf4\x03BAZ?github.com/orzkratos/errgen/internal/examples/example2;example2b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(ApiError)(0), // 0: api.ApiError
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
