// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: errors.proto

package example3

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessError int32

const (
	// Invalid request
	BusinessError_INVALID_REQUEST BusinessError = 0
	// Order not found
	BusinessError_ORDER_NOT_FOUND BusinessError = 1
	// Payment failed
	BusinessError_PAYMENT_FAILED BusinessError = 2
	// Insufficient inventory
	BusinessError_INSUFFICIENT_INVENTORY BusinessError = 3
	// Order expired
	BusinessError_ORDER_EXPIRED BusinessError = 4
)

// Enum value maps for BusinessError.
var (
	BusinessError_name = map[int32]string{
		0: "INVALID_REQUEST",
		1: "ORDER_NOT_FOUND",
		2: "PAYMENT_FAILED",
		3: "INSUFFICIENT_INVENTORY",
		4: "ORDER_EXPIRED",
	}
	BusinessError_value = map[string]int32{
		"INVALID_REQUEST":        0,
		"ORDER_NOT_FOUND":        1,
		"PAYMENT_FAILED":         2,
		"INSUFFICIENT_INVENTORY": 3,
		"ORDER_EXPIRED":          4,
	}
)

func (x BusinessError) Enum() *BusinessError {
	p := new(BusinessError)
	*p = x
	return p
}

func (x BusinessError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessError) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (BusinessError) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x BusinessError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessError.Descriptor instead.
func (BusinessError) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\bbusiness\x1a\x13errors/errors.proto*\x9a\x01\n" +
	"\rBusinessError\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x00\x12\x19\n" +
	"\x0fORDER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\x0ePAYMENT_FAILED\x10\x02\x1a\x04\xa8E\x92\x03\x12 \n" +
	"\x16INSUFFICIENT_INVENTORY\x10\x03\x1a\x04\xa8E\x99\x03\x12\x17\n" +
	"\rORDER_EXPIRED\x10\x04\x1a\x04\xa8E\x9a\x03\x1a\x04\xa0E\x90\x03BAZ?github.com/orzkratos/errgen/internal/examples/example3;example3b\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(BusinessError)(0), // 0: business.BusinessError
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
