// Code generated by protoc-gen-go-errors (errgen). DO NOT EDIT.

package example3

import (
	errors "github.com/go-kratos/kratos/v2/errors"
	newerk "github.com/orzkratos/errkratos/newerk"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// Unknown error
func IsGetUserResponseUnknown(err error) bool {
	return newerk.IsError(err, GetUserResponse_UNKNOWN, 500)
}

// Unknown error
func ErrorGetUserResponseUnknown(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, GetUserResponse_UNKNOWN, format, args...)
}

// User not found
func IsGetUserResponseUserNotFound(err error) bool {
	return newerk.IsError(err, GetUserResponse_USER_NOT_FOUND, 404)
}

// User not found
func ErrorGetUserResponseUserNotFound(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(404, GetUserResponse_USER_NOT_FOUND, format, args...)
}

// Access denied
func IsGetUserResponseAccessDenied(err error) bool {
	return newerk.IsError(err, GetUserResponse_ACCESS_DENIED, 403)
}

// Access denied
func ErrorGetUserResponseAccessDenied(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(403, GetUserResponse_ACCESS_DENIED, format, args...)
}

// Invalid username
func IsGetUserResponseInvalidUserId(err error) bool {
	return newerk.IsError(err, GetUserResponse_INVALID_USER_ID, 400)
}

// Invalid username
func ErrorGetUserResponseInvalidUserId(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(400, GetUserResponse_INVALID_USER_ID, format, args...)
}
